= Additional Information

== Legend

The demonstration snippets use the following terms to describe your actions:

* *Action* - Something you need to do. Notice that sometimes the action goes
before the explanation, and some times after. If an action takes a while, it is
better to start the action and then discuss it.
* *Explain* - This means you should explain what is happening. You do not need
to explain things at length, but you should not assume that everyone is clear
on everything that is happening.
* *Point out* - This means there are several items to point out in a larger
group of items. For example, you would point out a few lines in a JSON file but
not explain every line in the file.
* *Show* - Here you let the audience look at the screen and take everything in.
This is usually a good spot to ask for questions from the audience.
* *Ask* - This is where you could start a debate with the audience. For example,
 "How do you currently deal with scaling your applications?" Questions should be productive and ideally serve to address pain points that might occur when someone is showing the solution with the product.
* *Caution* - This event has the potential to put your demonstration at risk.
Pay attention to the warning.

:noaudio:

== Demonstration Tips

* _Carefully_ read what you are expected to do in each section.
* Do not assume anything--stick to the instructions.
* Do not just copy and paste. Try to understand what you are being asked to do
and whether you need to adjust values.
* Practice.
* Feel free to use your own words and flow through the demonstrations, as your
situation dictates. However, always remember the limitations of the environment.
* You can run the *Deployment_Post_Script.sh* file on your *ose_fastrax*
environment to practice, but its recommended to provision a fresh environment
for demonstrations.
