:scrollbar:
:data-uri:
:icons: images/icons
:toc2:

== How to Demonstrate OpenShift Enterprise 3.0

:numbered:

== Set up your Demonstration Environment

=== Provision Your Demonstration Environment 

To perform this demonstration, you must provision the demonstration environment. Provisioning ensures that you have access to an environment containing all the components you need to perform this demonstration. 

. Go to https://rhpds.redhat.com and use your credentials to log in to the OPENTLC labs provisioning system, which is built on top of Red Hat CloudForms to provide a self-service portal.
+
[TIP]
If you forgot your username or password, go to https://www.opentlc.com/pwm to reset your password or obtain a username reminder. 

. After you log in, navigate to *Services -> Catalogs -> All Services -> Cloud Infrastructure Demos*.

. On the left side of the screen, locate *OpenShift 3.0 Demo* and click the *Order* button that appears on the right.

. On the next screen, click *Submit* (on the lower right side) to order your environment. 
+
In a few minutes you will receive an email containing the details on how to connect to the environment.

. Wait about 20 minutes to allow the environment to build. Your environment includes the following entities:
** One host for the broker
** Two hosts for nodes
** One administration host for connection into the environment and miscellaneous tasks
** IPA


[WARNING] 
Do not attempt to use *App Control -> Start* after ordering the demo. The environment is already starting up. Using this command this may corrupt your environment or cause other complications. To receive an email with your environments status, select *Status*.

[NOTE]
Because the environment is all cloud-based, you can access it over the WAN from anywhere. You should not, however, expect performance to match a bare-metal environment.

=== Set Up SSH

To access any of your systems via SSH, you must use your personal OPENTLC SSO username and public SSH key. Unless otherwise noted, you cannot use SSH to connect directly as root.

If you have not already done so, you must provide a public SSH key. For information on generating an SSH key, see:

* Windows: 
link:http://kb.site5.com/shell-access-ssh/how-to-generate-ssh-keys-and-connect-to-your-account-with-putty[http://kb.site5.com/shell-access-ssh/how-to-generate-ssh-keys-and-connect-to-your-account-with-putty]

* Linux/OSX:
link:https://www.opentlc.com/ssh.html[https://www.opentlc.com/ssh.html]


[start=1]
. Go to https://www.opentlc.com/update and log in.  

. Paste your public key in that location.

. Connect to your administration host (`oselab-GUID.oslab.opentlc.com`) and make sure you can gain access to the master:
+
----

ssh -i ~/.ssh/yourprivatekey.key opentlc-username.com@oselab-GUID.oslab.opentlc.com

----
+
[NOTE]
The `GUID` is a four-character generated unique identifier assigned to your lab environment. You can find your `GUID` at the top of the lab provisioning email you received.
+
For example:
+
----

Laptop# ssh -i ~/.ssh/mykey.key shacharb-redhat.com@oselab-3x4m.oslab.opentlc.com

oselab-3x4m$ ssh root@192.168.0.100 # This is our Master host.

----


. Run the post-deployment script:
.. Connect to your master with the root user.
.. Run the script:
+
----

[sborenst@desktop01 ~]$ ssh -i ~/.ssh/sborenstkey.pub shacharb-redhat.com@oselab-*GUID*.oslab.opentlc.com

[bash-4.2$ ~] ssh root@192.168.0.100
root@192.168.0.100's password: ******** (ProvidedPassword) 

[root@master00-GUID ~]# sh Demo_Deployment_Script.sh

----

== Deploy From Prebuilt Containers (`hello-openshift` version)

In this scenario, Joe wants to deploy an application based on a container created by someone. 
 
=== Login and Authenticate  

. *Action* - Login to your server and switch to the user `joe`.
+
----

[sborenst@desktop01 ~]$ ssh -i ~/.ssh/sborenstkey.pub shacharb-redhat.com@oselab-*GUID*.oslab.opentlc.com

[bash-4.2$ ~] ssh root@192.168.0.100
root@192.168.0.100's password: ******** (ProvidedPassword) 

[root@master00-GUID ~]# su - joe

----

. *Action* - As user `joe` log in to OpenShift and select the `hello-openshift` project.
+
** *Caution* - If you have _already logged in_ to OpenShift Enterprise, _do not_ run the `osc login` command again. Because you are already logged in, this will result in an error on screen.
** *Explain* that you are currently logging in to the master as part of this demonstration, but consider that every command that `joe` issues is a command that a developer would do on his or her laptop or workstation, or from wherever he or she is working. 
** *Explain* what projects are and how different projects could have different user permissions and quotas attached to them.
+
----

[joe@master00~]$ osc login -u joe \
--certificate-authority=/var/lib/openshift/openshift.local.certificates/ca/cert.crt \
--server=https://`hostname -f`:8443
Password: (Enter ProvidedPassword)
Login successful.
[joe@master00~]$ osc project hello-openshift
Using project "hello-openshift"

----

=== Define the Pod 

Here you define the pod, but not the service, replication controllers, or routes.

. *Show* the `hello-openshift-podonly.json` file.
** *Explain* that this is a very simple pod definition example and it does not cover services, routes, and other resources.
** *Point out* the following: 
*** `name` - This is the name of the pod. 
*** `image` - This is the container image that this pod is running. This can be a local registry or an external one (like `docker.io`).
*** `ports` - These are the ports that the Docker container exposes. Your code and application need to listen on those ports as well.
*** `labels` - This is perhaps the most important component. Labels are "tags" that you apply, so that you can refer to a group of resources (pods, services, and so on).
+
[source,json]
----

[joe@master00~]$ cat hello-openshift-pod.json 
{
  "id": "hello-openshift-pod",
  "kind": "Pod",
  "apiVersion":"v1beta2",
  "labels": {
    "name": "hello-openshift-singlesadpod"
  },
  "desiredState": {
    "manifest": {
      "version": "v1beta1",
      "id": "hello-openshift-singlesadpod",
      "containers": [{
        "name": "hello-openshift-singlesadpod",
        "image": "openshift/hello-openshift",
        "ports": [{
          "containerPort": 8080
        }]
      }]
    }
  }
}

----

=== Create the Pod 

Here you create the pod, but not the service, replication controllers, or routes.

. *Action* - Use the `osc create` command to create the pod from the `hello-openshift-pod.json` file.
** *Explain* that during this process, OpenShift Enterprise reviews and processes the file. You could easily have added other pods or resources into the file, and OpenShift Enterprise would have processed them together. 
. *Optional* - You can use the `docker ps` command to show the running container and the `docker logs -f $DOCKERPID&` command to show the internal Docker log for the container being built. 
+
----

[joe@master00~]$ osc create -f hello-openshift-pod.json
pods/hello-openshift-pod 

---- 


. *Action* - Run *osc get pods* to show the pod status and that you can access the pod locally.
** *Explain* the output to the audience.
** *Point out* the following: 
*** `node` - The node the pod is running on.
*** `label` - The label you have marked the pod with.
*** `name` - The pod name.
*** `ip` and `port` - The IP and port that the pod is "listening" on. Keep in mind that this is not the port you will expose to the outside world.
+
----

[joe@master00~]$ osc get pods 


[joe@master00~]$ curl http://${pod.ip}:${pod.port}
You will get some html output back 

----
 
NOTE: The container will be up in a few seconds, but the application in the container might take a few minutes to load.


=== Deploy a Complete Application With Service and Route to Match 

. *Action* - Review the following complete application example `hello-openshift-complete.json` file.
** *Ask* how complicated or simple it would be to define a full application stack in the audience's current environment. 
** *Point out* the following:
+
[NOTE]
You should understand every line in the file in case the audience asks questions. However, do not explain each line.

*** `"kind": "Service"` - Explain what a service is and that here you are creating a "front end" for this pod or group of pods.
*** `"kind": "Route"` - Explain that a route resource allows external access using a HAProxy container. You could have many routes to the same application. 
*** `"replicas": 1` - Explain that you currently set this pod to have a single replica. If you want to deploy many replicas or scale out at any time, you can simply change this value. 
*** `"labels":` - The label you enter here is applied to each resource item you create for this application. This simplifies management. 
*** `"triggers":` - This is an optional component. Explain that you can set triggers to redeploy containers under certain conditions--for example, if a newer image is available.

+
[source,json]
----

[joe@master00~]$ cat hello-openshift-complete.json
{
  "metadata":{
    "name":"hello-openshift-meta"
  },
  "kind":"Config",
  "apiVersion":"v1beta1",
  "creationTimestamp":"2014-09-18T18:28:38-04:00",
  "items":[
    {
      "id": "hello-openshift-service",
      "kind": "Service",
      "apiVersion": "v1beta1",
      "port": 3030,
      "containerPort": 8080,
      "selector": {
        "name": "hello-openshift"
      }
    },
    {
      "kind": "Route",
      "apiVersion": "v1beta1",
      "metadata": {
        "name": "hello-openshift-route"
      },
      "id": "hello-openshift-route",
      "host": "hello-openshift.cloudapps-$GUID.oslab.opentlc.com",
      "serviceName": "hello-openshift-service"
    },
    {
        "kind": "DeploymentConfig",
        "apiVersion": "v1beta1",
        "metadata": {
            "name": "hello-openshift"
        },
        "triggers": [
            {
              "imageChangeParams": {
                "automatic": true,
                "containerNames": [
                  "hello-openshift"
                ],
                "from": {
                  "name": "hello-openshift"
                },
                "tag": "latest"
              },
              "type": "ImageChange"
            }
        ],
        "template": {
            "strategy": {
                "type": "Recreate"
            },
            "controllerTemplate": {
                "replicas": 1,
                "replicaSelector": {
                    "name": "hello-openshift"
                },
                "podTemplate": {
                    "desiredState": {
                        "manifest": {
                            "version": "v1beta2",
                            "id": "hello-openshift",
                            "volumes": null,
                            "containers": [
                                {
                                    "name": "hello-openshift",
                                    "image": "openshift/hello-openshift",
                                    "ports": [
                                        {
                                        	 "containerPort": 8080,
                                        	   "protocol": "TCP"
                                                              }
                                    ],
                                    "resources": {},
                                    "terminationMessagePath": "/dev/termination-log",
                                    "imagePullPolicy": "PullIfNotPresent",
                                    "capabilities": {}
                                }
                            ],
                            "restartPolicy": {
                                "always": {}
                            },
                            "dnsPolicy": "ClusterFirst"
                        }
                    },
                    
                    "labels": {
                        "name": "hello-openshift"
                    }
                }
            }
        },
        "latestVersion": 1
    }
  ]
}


----

. *Action* - Create your application using the *osc create* command. 
** *Explain* that by passing the `.json` file to OpenShift Enterprise, you are requesting all the resource items in the file to be created.
** *Optional* - Show your audience the web console.
.. *Ask* the audience for any questions. This is a good time to find out, for example, if the process is clear, or if they see themselves using this tool.
+
----

[joe@master00~]$ osc create -f hello-openshift-complete.json

----


=== Show the Application Using Your Browser
 
. *Action* - Browse to: link:http://hello-openshift.cloudapps-$GUID.oslab.opentlc.com[http://hello-openshift.cloudapps-$GUID.oslab.opentlc.com]
** *Explain* that you have now  deployed a container that is externally accessible. You could scale the application at any time, and the route and service ensure that traffic always routes to the application.
** *Big finish* - Offer some closing words on this demo.


=== Show the Application Using the Command Line 

. *Action* - You can run the following commands to show the application resources from the command line
.. *Show* The audience that you now have a Pod, a ReplicationController (RC) and a DeploymentConfig (DC)
.. *Explain* the roles of the RC and DC resources.
.. *Point Out:*
... The differences between the single sad pod from the beginning of this demonstration and the pod that was generated by our DC and RC
... That when we run *osc get rc* and see our RCs we can see how many replicas we are running.  
----
[joe@master00-70ac ~]$ osc get pods
POD                       IP         CONTAINER(S)                   IMAGE(S)                    HOST                                            LABELS                                                                               STATUS    CREATED
hello-openshift-1-ok0aa   10.1.0.6   hello-openshift                openshift/hello-openshift   master00-70ac.oslab.opentlc.com/192.168.0.100   deployment=hello-openshift-1,deploymentconfig=hello-openshift,name=hello-openshift   Running   About a minute
hello-openshift-pod       10.1.0.5   hello-openshift-singlesadpod   openshift/hello-openshift   master00-70ac.oslab.opentlc.com/192.168.0.100   name=hello-openshift-singlesadpod                                                    Running   2 minutes
[joe@master00-70ac ~]$ osc get dc 
NAME              TRIGGERS      LATEST VERSION
hello-openshift   ImageChange   1
[joe@master00-70ac ~]$ osc get rc 
CONTROLLER          CONTAINER(S)      IMAGE(S)                    SELECTOR                                                                             REPLICAS
hello-openshift-1   hello-openshift   openshift/hello-openshift   deployment=hello-openshift-1,deploymentconfig=hello-openshift,name=hello-openshift   1

[joe@master00-70ac ~]$ curl http://hello-openshift.cloudapps-$GUID.oslab.opentlc.com
Hello OpenShift!
----

=== Optional - Show how to increase the replicas of the deployed pods.

. *Action* - Run the following command. 
.. *Explain the role of the DC (DeploymentConfig)
.. *Point Out:*
... Triggers - What makes the DC redeploy the pods
... Replicas - How many replicas are required of this pod - This is where we will make a permanent change to an environment

----

[joe@master00-70ac ~]$ osc describe dc hello-openshift
Name:		hello-openshift
Created:	6 minutes ago
Labels:		<none>
Latest Version:	1
Triggers:	Image(hello-openshift@latest, auto=true)
Strategy:	Recreate
Template:
	Selector:	name=hello-openshift
	Replicas:	1
	Containers:
		NAME		IMAGE				ENV
		hello-openshift	openshift/hello-openshift	
Latest Deployment:
	Name:		hello-openshift-1
	Status:		Complete
	Selector:	deployment=hello-openshift-1,deploymentconfig=hello-openshift,name=hello-openshift
	Labels:		
	Replicas:	5 current / 5 desired
	Pods Status:	5 Running / 0 Waiting / 0 Succeeded / 0 Failed

---- 


. *Action* - Run the following command.
.. *Action* - Edit the RC replication controller and change the Replica count from 1 to 5, save and exit (This is vi editor)
.. *Explain* By changing the Replication Controller we are raising the replica count from 1 to 5, this will result in immediate change but will not be saved permanently, if we wanted to make a permanent change we will do the same to the DC.

----
 
[joe@master00-70ac ~]$ osc edit rc hello-openshift-1
replicationcontrollers/hello-openshift-1


----

. *Action* - Run the following commands to show the the new replicas that were created and that the service has updated with the new pods.
.. *Explain* that new pods are created by the RC the next time it syncs and that the Service will be updated with the new pod names as they appear. 

----

[joe@master00-70ac ~]$ osc get pods
POD                       IP          CONTAINER(S)                   IMAGE(S)                    HOST                                            LABELS                                                                               STATUS    CREATED
hello-openshift-1-0yuij   10.1.0.8    hello-openshift                openshift/hello-openshift   master00-70ac.oslab.opentlc.com/192.168.0.100   deployment=hello-openshift-1,deploymentconfig=hello-openshift,name=hello-openshift   Running   10 seconds
hello-openshift-1-exegq   10.1.0.7    hello-openshift                openshift/hello-openshift   master00-70ac.oslab.opentlc.com/192.168.0.100   deployment=hello-openshift-1,deploymentconfig=hello-openshift,name=hello-openshift   Running   10 seconds
hello-openshift-1-h2qx7   10.1.0.10   hello-openshift                openshift/hello-openshift   master00-70ac.oslab.opentlc.com/192.168.0.100   deployment=hello-openshift-1,deploymentconfig=hello-openshift,name=hello-openshift   Running   9 seconds
hello-openshift-1-ii1du   10.1.0.9    hello-openshift                openshift/hello-openshift   master00-70ac.oslab.opentlc.com/192.168.0.100   deployment=hello-openshift-1,deploymentconfig=hello-openshift,name=hello-openshift   Running   9 seconds
hello-openshift-1-ok0aa   10.1.0.6    hello-openshift                openshift/hello-openshift   master00-70ac.oslab.opentlc.com/192.168.0.100   deployment=hello-openshift-1,deploymentconfig=hello-openshift,name=hello-openshift   Running   About a minute
hello-openshift-pod       10.1.0.5    hello-openshift-singlesadpod   openshift/hello-openshift   master00-70ac.oslab.opentlc.com/192.168.0.100   name=hello-openshift-singlesadpod                                                    Running   2 minutes

[joe@master00-70ac ~]$ osc describe service hello-openshift-service
Name:                   hello-openshift-service
Labels:                 <none>
Selector:               name=hello-openshift
IP:                     172.30.17.248
Port:                   <unnamed>       3030/TCP
Endpoints:              10.1.0.10:8080,10.1.0.6:8080,10.1.0.7:8080...
Session Affinity:       None
No events.


----

== Deploy From Prebuilt Containers (`weightwatcher` version)
 
In this scenario, Joe wants to deploy an application based on a container someone created. 
 
=== Log In and Authenticate 

. *Action* - Log in to your server and switch to the user `joe`:
+
----

[sborenst@desktop01 ~]$ ssh -i ~/.ssh/sborenstkey.pub shacharb-redhat.com@oselab-*GUID*.oslab.opentlc.com

[bash-4.2$ ~] ssh root@192.168.0.100
root@192.168.0.100's password: ******** (ProvidedPassword) 

[root@master00-GUID ~]# su - joe

----

. *Action* - As user `joe`, log in to OpenShift Enterprise and select the `weightwatcher` project.
+
** *Caution* - If you have _already logged in_ to OpenShift Enterprise, _do not_ run the `osc login` command again. Because you are already logged in, this will result in an error on screen. 
** *Explain* that you are currently logging in to the master as part of this demonstration, but consider that every command that `joe` issues is a command that a developer would do on his or her laptop or workstation, or from wherever he or she is working. 
** *Explain* what projects are and how different projects could have different user permissions and quotas attached to them. 
+
----

[joe@master00~]$ osc login -u joe \
--certificate-authority=/var/lib/openshift/openshift.local.certificates/ca/cert.crt \
--server=https://`hostname -f`:8443
Password: (Enter ProvidedPassword)
Login successful.
[joe@master00~]$ osc project weightwatcher
Using project "weightwatcher"

----

=== Define the Pod

Here you define the pod, but not the service, replication controllers, or routes.

. *Show* the following simple pod example `weightwatcher-podonly.json` file.
** *Explain* that this is a very simple pod definition example and does not cover services, routes, or other resources.
** *Point out* the following: 
*** `name` - This is the name of the pod. 
*** `image` - This is the container image that this pod is running. This can be a local registry or an external one (like `docker.io`).
*** `ports` - These are the ports that the Docker container exposes. Your code and application need to listen on those ports as well.
*** `labels` - This is perhaps the most important component. Labels are "tags" that you apply, so that you can refer to a group of resources (pods, services, and so on).
+
[source,json]
----

[joe@master00~]$ cat weightwatcher-pod.json 
{
 "id": "weightwatcher-pod",
 "kind": "Pod",
 "apiVersion":"v1beta2",
 "labels": {
 "name": "weightwatcher-singlesadpod"
 },
 "desiredState": {
 "manifest": {
 "version": "v1beta1",
 "id": "weightwatcher-singlesadpod",
 "containers": [{
 "name": "weightwatcher-singlesadpod",
 "image": "spicozzi/weightwatcher",
 "ports": [{
 "containerPort": 8080
 }]
 }]
 }
 }
}

----

=== Create the Pod

Here you create the pod, but not the service, replication controllers, or routes.

. *Action* - Run the `osc create` command to create the pod from the `weightwatcher-pod.json` file.
** *Explain* that during this process, OpenShift Enterprise reviews and processes the file. You could easily have added other pods or resources into the file, and OpenShift Enterprise would have processed them together. 
. *Optional* - You can use the `docker ps` command to show the running container and the `docker logs -f $DOCKERPID&` command to show the internal Docker log for the container being built. 
+
----

[joe@master00~]$ osc create -f weightwatcher-pod.json
pods/weightwatcher-pod 

---- 


. *Action* - Run `osc get pods` to show the pod status and that you can access the pod locally.
** *Explain* the output to the audience.
** *Point out* the following: 
*** `node` - The node the pod is running on.
*** `label` - The label you have marked the pod with.
*** `name` - The pod name.
*** `ip` and `port` - The IP and port that the pod is "listening" on. Keep in mind that this is not the port you will expose to the outside world.
+
----

[joe@master00~]$ osc get pods 


[joe@master00~]$ curl http://${pod.ip}:${pod.port}
You will get some html output back 

----
+
[NOTE]
The container is available in a few seconds, but the application in the container might take a few minutes to load.


=== Deploy a Complete Application With Service and Route to Match 

. *Action* - Review the following complete application example `weightwatcher-complete.json` file.
** *Explain* that this is a complete application definition file. It might look daunting at first, but it is a simple collection of resources similar to what the audience saw in the simple pod example.
** *Ask* how complicated or simple it would be to define a full application stack in the audience's current environment. 
** *Point out* the following:
+
[NOTE]
You should understand every line in the file in case the audience asks questions. However, do not explain each line.

*** `"kind": "Service"` - Explain what a service is and that here you are creating a "front end" for this pod or group of pods.
*** `"kind": "Route"` - Explain that a route resource allows external access using a HAProxy container. You could have many routes to the same application. 
*** `"replicas": 1` - Explain that you currently set this pod to have a single replica. If you want to deploy many replicas or scale out at any time, you can simply change this value. 
*** `"labels":` - The label you enter here is applied to each resource item you create for this application. This simplifies management. 
*** `"triggers":` - This is an optional component. Explain that you can set triggers to redeploy containers under certain conditions--for example, if a newer image is available.
+
[source,json]
----

[joe@master00~]$ cat weightwatcher-complete.json
{
 "metadata":{
 "name":"weightwatcher-meta"
 },
 "kind":"Config",
 "apiVersion":"v1beta1",
 "creationTimestamp":"2014-09-18T18:28:38-04:00",
 "items":[
 {
 "id": "weightwatcher-service",
 "kind": "Service",
 "apiVersion": "v1beta1",
 "port": 3030,
 "containerPort": 8080,
 "selector": {
 "name": "weightwatcher"
 }
 },
 {
 "kind": "Route",
 "apiVersion": "v1beta1",
 "metadata": {
 "name": "weightwatcher-route"
 },
 "id": "weightwatcher-route",
 "host": "weightwatcher.cloudapps-$GUID.oslab.opentlc.com",
 "serviceName": "weightwatcher-service"
 },
 {
 "kind": "DeploymentConfig",
 "apiVersion": "v1beta1",
 "metadata": {
 "name": "weightwatcher"
 },
 "triggers": [
 {
 "imageChangeParams": {
 "automatic": true,
 "containerNames": [
 "weightwatcher"
 ],
 "from": {
 "name": "weightwatcher"
 },
 "tag": "latest"
 },
 "type": "ImageChange"
 }
 ],
 "template": {
 "strategy": {
 "type": "Recreate"
 },
 "controllerTemplate": {
 "replicas": 1,
 "replicaSelector": {
 "name": "weightwatcher"
 },
 "podTemplate": {
 "desiredState": {
 "manifest": {
 "version": "v1beta2",
 "id": "weightwatcher",
 "volumes": null,
 "containers": [
 {
 "name": "weightwatcher",
 "image": "spicozzi/weightwatcher",
 "ports": [
 {
 	 "containerPort": 8080,
 	 "protocol": "TCP"
 }
 ],
 "resources": {},
 "terminationMessagePath": "/dev/termination-log",
 "imagePullPolicy": "PullIfNotPresent",
 "capabilities": {}
 }
 ],
 "restartPolicy": {
 "always": {}
 },
 "dnsPolicy": "ClusterFirst"
 }
 },
 
 "labels": {
 "name": "weightwatcher"
 }
 }
 }
 },
 "latestVersion": 1
 }
 ]
}


----

. *Action* - Create your application using the `osc create` command.
** *Explain* that by passing the JSON file to OpenShift Enterprise, you are requesting all the resource items in the file to be created.
** *Optional* - Show your audience the web console.
** *Ask* the audience for any questions. This is a good time to find out, for example, if the process is clear, or if they see themselves using this tool.
+
----

[joe@master00~]$ osc create -f weightwatcher-complete.json

----

=== Show the Application Using Your Browser 

. *Action* - Browse to: link:weightwatcher.cloudapps-$GUID.oslab.opentlc.com/business-central[weightwatcher.cloudapps-$GUID.oslab.opentlc.com/business-central].
. *Action* - Log in using the following credentials : *erics/jbossbrms1!*. 
** *Explain* that you have now deployed a container that is externally accessible. You could scale the application at any time, and the route and service ensure that traffic always routes to the application. 
** *Big finish* - Offer some closing words on this demo.

== Deploy From an Existing Git Repository (Web Console, STI Build)

In this scenario, Joe wants to deploy and test an application from an existing Git repository.

=== Review the Target Git Repository and Log In to the OpenShift Web Console

. *Action* - Browse to link:https://github.com/openshift/simple-openshift-sinatra-sti[https://github.com/openshift/simple-openshift-sinatra-sti].
** *Explain* that what you see here is a Git repository containing a sample Ruby application using the Sinatra Ruby Gem.

** *Optional* - Review the files briefly with the audience if you think it would help them understand.
. *Action* - Browse to link:https://master00-GUID.oslab.opentlc.com:8443[https://master00-GUID.oslab.opentlc.com:8443] and log in using the `joe` account with password `R3dh4t1!`.
+
[NOTE]
*GUID* in the URL refers to your Global Unique Identifier.
+
** *Explain* that you are currently logging into the OpenShift web console as the user `joe`.
** *Point out* the following:
*** You can create users locally or link to an enterprise directory. 
*** You can group users and create working teams.
*** You can use quotas to set resource limits for users, projects, and teams.

=== Deploy Your STI Application

. *Action* - Select the *SourceToImage* project. 
. *Action* - Click the *Create* button.
. *Action* - Paste the Git repository into the *Source Repository* text box: link:https://github.com/openshift/simple-openshift-sinatra-sti[https://github.com/openshift/simple-openshift-sinatra-sti].
** *Explain* that you are creating a new application. To do that, you need to provide OpenShift Enterprise with two key pieces of information:
*** The source code repository 
*** The builder image or the base image on which to build the container 

. *Action* - Click the blue arrow to progress to the next step, and select *"ruby-20-rhel7:latest"*. 
** *Explain* that you picked the *ruby-20-rhel7:latest* image as your builder image. The code and all of its dependencies will be layered on top of this image.
** *Explain* that you can have OpenShift Enterprise automatically rebuild and redeploy the entire application if an image update occurs.
** *Explain* that you can have different `ImageStreams`. You can deploy from either certified Red Hat builder images or your own.

. *Action* - Confirm your selection by clicking *Select this Image*. 
** *Show* and *explain* that next you select the application attributes, such as ports, routes, triggers, and more.

. *Action* - Set the name of the application to `simplerubyapp`.
** *Show* that you can select to have a route for the application or not.
** *Show* that you can change the port the application listens on. 
** *Show* that you can select the number of replicas the application has.
** *Show* that you can set a label for the application to manage it by label.

. *Action* - Click *Create*.
** *Show* that you got a successful message stating "All resources for application `simplerubyapp` were created successfully."
** *Show* that there are currently no pods created. 
+
[NOTE]
The web console should refresh shortly to indicate that a build was started.

=== The Build Process

. *Explain* that this Beta version does not have a *Build* button, so you will trigger the build manually.
. *Action* - Connect as user `joe` to your master host and authenticate to OpenShift Enterprise using the `osc login` command.
** *Caution* - If you have _already logged in_ to OpenShift Enterprise, _do not_ run the `osc login` command again. You are already logged in, and this will result in an error on the screen. 
+
----

[joe@master00~]$ osc login -u joe \
--certificate-authority=/var/lib/openshift/openshift.local.certificates/ca/cert.crt \
--server=https://`hostname -f`:8443
Password: (Enter ProvidedPassword)
Login successful.


----

. *Action* - Switch to the `sourcetoimage` project:
+
----

[joe@master00~]$ osc project sourcetoimage

----

. *Action* - Start the build using the `osc start-build` command. 
** *Explain* that you can see that you requested a build process and that you can follow the build log using simple commands.
** *Point out* a few lines to explain to your audience if they are so inclined. For example, you can point out the following: 
*** The image that OpenShift Enterprise is selecting and importing
*** The repository read and dependencies installed (Sinatra Gem)
+
----

[joe@master00-31c5]$ osc start-build simplerubyapp -n sourcetoimage

[joe@master00-31c5]$ osc get builds
NAME TYPE STATUS POD
simplerubyapp-1 STI Running simplerubyapp-1

[joe@master00-31c5 openshift]$ osc build-logs simplerubyapp-1
2015-05-18T07:53:24.879122533Z I0518 03:53:24.605490 1 sti.go:54] Creating a new STI builder with build request: &api.Request{BaseImage:"registry.access.redhat.com/openshift3_beta/ruby-20-rhel7:latest", Do
ckerSocket:"unix:///var/run/docker.sock", PreserveWorkingDir:false, Source:"https://github.com/openshift/simple-openshift-sinatra-sti", Ref:"master", Tag:"172.30.17.207:5000/demo/simplerubyapp", Incremental:true
, RemovePreviousImage:false, Environment:map[string]string{"OPENSHIFT_BUILD_REFERENCE":"master", "OPENSHIFT_BUILD_NAME":"simplerubyapp-1", "OPENSHIFT_BUILD_NAMESPACE":"demo", "OPENSHIFT_BUILD_SOURCE":"https://gi
thub.com/openshift/simple-openshift-sinatra-sti"}, CallbackURL:"", ScriptsURL:"", Location:"", ForcePull:false, WorkingDir:"", LayeredBuild:false, InstallDestination:"", Quiet:false, ContextDir:""}
...
...
...

[joe@master00-31c5]$ osc get pods

----

. While you wait for the build to complete, *explain* the concepts of _service resources_ and _route resources_.
** *Show* the service created for this application under *Browse -> Services* in the web console.
** *Explain* services. 
** *Show* that the route for the application was set. 

. *Optional* - Add the route manually for the environment.
** *Action* - Run the following command to create a route for the application.
** *Caution* - Make sure that the GUID value is populated correctly. Review the file and make sure that the `host:` value is set correctly.
** *Explain* that in the current beta version, you do not use the web console to set routes. In the near future, you will be able to do all this in the web console.
** *Explain* that in this scenario, you decided to add another route to your application, so it is available under another URL. 
** *Explain* that you are creating a route so that when a user resolves `simplerubyapp.cloudapps-$GUID.oslab.opentlc.com`, you will route the user to one of the pods under the `simplerubyapp` service. 
** *Show* - After running the `osc create` command, you can use curl or your browser to see the application at link:http://simplerubyapp.cloudapps-$GUID.oslab.opentlc.com[http://simplerubyapp.cloudapps-$GUID.oslab.opentlc.com].
+
[source,json]
----

[joe@master00 ~]$ cat simplerubyapp-route.json 
{
 "kind": "Route",
 "apiVersion": "v1beta1",
 "metadata": {
 "name": "simplerubyapp-route"
 },
 "id": "simplerubyapp-route",
 "host": "simplerubyapp.cloudapps-$GUID.oslab.opentlc.com",
 "serviceName": "simplerubyapp"
}

[joe@master00 ~]$ osc create -f simplerubyapp-route.json
 
----

=== Complete the Demonstration

. *Action* - Browse to: link:http://simplerubyapp.cloudapps-$GUID.oslab.opentlc.com[http://simplerubyapp.cloudapps-$GUID.oslab.opentlc.com]. 
** *Explain* what you did, and that this is a very common workflow for every development environment.
** *Point out* the following: 
*** You created an image from a Git repository and a builder image.
*** You created a service that acts as a list that represents all of your pods.
*** You created a route to direct to that service. 
*** STI builds _do not_ need to recreate the image every time. When the code changes, the builds just "add a layer" with the code. 

== Deploy a Two-Tiered Application From a Template (Web Console and Command Line)

In this scenario, Joe wants to deploy a two-tiered `Web-DB` application using an `Instant Apps` template.

=== Deploy Your Application Using the Web Console

. *Action* - Browse to the OpenShift Enterprise web console: link:https://master00-GUID.oslab.opentlc.com:8443[https://master00-GUID.oslab.opentlc.com:8443]. 
+
[NOTE]
Remember that *GUID* in the URL refers to your Global Unique Identifier.
 
. *Action* - Log in using the `joe` account with password `R3dh4t1!`.
** *Explain* - I am currently logging into the OpenShift Enterprise web console as the user `joe`.
** *Point out* the following:
*** You can create users locally or link to an enterprise directory. 
*** You can group users and create teams.
*** You can use quotas to set resource limits on users, projects, and teams.

. *Action* - Select the `Instant Apps Demonstration` project. 
. *Action* - Click the *Create* button.
. *Action* Click `instantapp-2tier-application`.
** *Explain* that you are now creating a new application from a template that was loaded in the OpenShift Enterprise environment.

. *Action* - Click the *Select Template* box. 
** *Explain* that you need to review the images and edit the application attributes, such as labels and parameters.
** *Show* that you can set a label for the application to manage it by label.
** *Show* that parameters such as usernames and credentials are generated for each template, but you can also set them manually. 

. *Action* - Click *Create*.
** *Explain* what is about to happen: Builds are getting started and services are being created for the front end and back end.
. *Optional* - Select *Browse* on the left side of the screen and show the *Builds*, *Services*, and *Pods* panes. 

=== Log In and Authenticate 

. *Action* - Log in to your server and switch to the user `joe`:
+
----

[sborenst@desktop01 ~]$ ssh -i ~/.ssh/sborenstkey.pub shacharb-redhat.com@oselab-*GUID*.oslab.opentlc.com

[bash-4.2$ ~] ssh root@192.168.0.100
root@192.168.0.100's password: ******** (ProvidedPassword) 

[root@master00-GUID ~]# su - joe

----

. *Action:* - As user `joe`, log in to OpenShift Enterprise and select the `instantapps` project.
+
** *Caution* - If you have _already logged in_ to OpenShift Enterprise, _do not_ run the `osc login` command again. You are already logged in, and this will result in an error on the screen. 
** *Explain* that you are currently logging in to the master as part of this demonstration, but consider that every command that `joe` issues is a command that the developer could do on his or her laptop or workstation, or from wherever he or she is working. 
** *Explain* what projects are and how different projects could have different user permissions and quotas attached to them. 
+
----

[joe@master00~]$ osc login -u joe \
--certificate-authority=/var/lib/openshift/openshift.local.certificates/ca/cert.crt \
--server=https://`hostname -f`:8443
Password: (Enter ProvidedPassword)
Login successful.

[joe@master00~]$ osc project instantapps
Using project "instantapps"

----


=== Review the Build Process 

. *Action* - Run the following commands to display the current process.
** *Explain* the process the audience is seeing and the different resources that you created.
** *Point out* the following
*** The `service` resource created for `frontend` and `backend`
*** The `route` resource created for the `frontend`
+
----

[joe@master00-08b3 ~]$ osc get builds
NAME TYPE STATUS POD
ruby-sample-build-1 STI Complete ruby-sample-build-1

[joe@master00-08b3 ~]$ osc build-logs ruby-sample-build-1
2015-05-20T04:00:01.733176474Z I0520 00:00:01.691499 1 sti.go:54] Creating a new STI builder with build request: &api.Request{BaseImage:"registry.access.redhat.com/openshift3_beta/ruby-20-rhel7:latest", DockerSocket:"unix:///var/run/docker.sock", PreserveWorkingDir:false, Source:"git://github.com/openshift/ruby-hello-world.git", Ref:"beta3", Tag:"172.30.17.15:5000/instantapps/origin-ruby-sample", Incremental:true, RemovePreviousImage:false, Environment:map[string]string{"OPENSHIFT_BUILD_SOURCE":"git://github.com/openshift/ruby-hello-world.git", "OPENSHIFT_BUILD_REFERENCE":"beta3", "OPENSHIFT_BUILD_NAME":"ruby-sample-build-1", "OPENSHIFT_BUILD_NAMESPACE":"instantapps"}, CallbackURL:"", ScriptsURL:"", Location:"", ForcePull:false, WorkingDir:"", LayeredBuild:false, InstallDestination:"", Quiet:false, ContextDir:""}
...
...
2015-05-20T04:01:12.286429447Z I0520 00:01:12.284330 1 sti.go:78] Pushing 172.30.17.15:5000/instantapps/origin-ruby-sample image ...
2015-05-20T04:01:32.977841550Z I0520 00:01:32.973896 1 sti.go:83] Successfully pushed 172.30.17.15:5000/instantapps/origin-ruby-sample
 
[joe@master00-08b3 ~]$ osc get pods
POD IP CONTAINER(S) IMAGE(S) HOST LABELS STATUS CREATED
database-1-nyeyf 10.1.0.12 ruby-helloworld-database registry.access.redhat.com/openshift3_beta/mysql-55-rhel7 master00-08b3.oslab.opentlc.com/192.168.0.100 deployment=database-1,deploymentconfig=database,name=database,template=application-template-stibuild Running 8 minutes
deployment-frontend-1-hook-ip7b3 lifecycle 172.30.17.15:5000/instantapps/origin-ruby-sample:07208526cf7644f6291ca21776e84be97d4bcbae1082b173eb11efd8a758e338 master00-08b3.oslab.opentlc.com/192.168.0.100 <none> Failed 6 minutes
deployment-frontend-1-hook-lyqwn lifecycle 172.30.17.15:5000/instantapps/origin-ruby-sample:07208526cf7644f6291ca21776e84be97d4bcbae1082b173eb11efd8a758e338 master00-08b3.oslab.opentlc.com/192.168.0.100 <none> Succeeded 6 minutes
frontend-1-mss2w 10.1.0.17 ruby-helloworld 172.30.17.15:5000/instantapps/origin-ruby-sample:07208526cf7644f6291ca21776e84be97d4bcbae1082b173eb11efd8a758e338 master00-08b3.oslab.opentlc.com/192.168.0.100 deployment=frontend-1,deploymentconfig=frontend,name=frontend,template=application-template-stibuild Running 6 minutes
ruby-sample-build-1 sti-build openshift3_beta/ose-sti-builder:v0.4.3.2 master00-08b3.oslab.opentlc.com/192.168.0.100 build=ruby-sample-build-1,buildconfig=ruby-sample-build,name=ruby-sample-build,template=application-template-stibuild Succeeded 8 minutes
 
----


=== Complete the Demonstration

. *Action* - Browse to: link:http://instantapp.cloudapps-$GUID.oslab.opentlc.com[instantapp.cloudapps-$GUID.oslab.opentlc.com].
** *Explain* what you did, and that this is a very common workflow for every development environment.
** *Point out* the following: 
*** You created a Ruby front end and a database backend.
*** Using the template, both parts of the application environment can share values like usernames and passwords.
*** You can randomize and generate values for each template. 
*** You created a route to direct to the front end service. 

:numbered!:

